--------------------------------------------------------
--  File created - Monday-December-11-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CENTRE
--------------------------------------------------------

  CREATE TABLE "FAROUK"."CENTRE" 
   (	"ID" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"LIEU" VARCHAR2(20 BYTE), 
	"SURFACE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "FAROUK"."CLIENT" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"ID" VARCHAR2(20 BYTE), 
	"TYPEC" VARCHAR2(20 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE), 
	"MAIL" VARCHAR2(35 BYTE), 
	"REVENUS" FLOAT(126), 
	"RIB" NUMBER, 
	"REF" NUMBER, 
	"DATE_PAYEMENT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "FAROUK"."EMPLOYE" 
   (	"CIN" VARCHAR2(20 BYTE), 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"DATENAISS" VARCHAR2(20 BYTE), 
	"SALAIRE" VARCHAR2(20 BYTE), 
	"POSTE" VARCHAR2(20 BYTE), 
	"DEPART" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"ID_CENTRE" VARCHAR2(20 BYTE), 
	"LOGIN" VARCHAR2(20 BYTE), 
	"CARD_UID" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "FAROUK"."PRODUIT" 
   (	"REF" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"ETAT" VARCHAR2(20 BYTE), 
	"QT" NUMBER, 
	"PRIX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table VENDRE
--------------------------------------------------------

  CREATE TABLE "FAROUK"."VENDRE" 
   (	"CIN_EMPLOYE" VARCHAR2(20 BYTE), 
	"REF_PRODUIT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into FAROUK.CENTRE
SET DEFINE OFF;
Insert into FAROUK.CENTRE (ID,NOM,LIEU,SURFACE) values ('2134','123','12','12');
Insert into FAROUK.CENTRE (ID,NOM,LIEU,SURFACE) values ('453','45','beja','45');
Insert into FAROUK.CENTRE (ID,NOM,LIEU,SURFACE) values ('2424','45','sousse','45');
REM INSERTING into FAROUK.CLIENT
SET DEFINE OFF;
Insert into FAROUK.CLIENT (NOM,PRENOM,ID,TYPEC,ADRESSE,MAIL,REVENUS,RIB,REF,DATE_PAYEMENT) values ('FAROUK',null,'123123','client fidele','123','123',123,0,123,to_date('01-JAN-00','DD-MON-RR'));
Insert into FAROUK.CLIENT (NOM,PRENOM,ID,TYPEC,ADRESSE,MAIL,REVENUS,RIB,REF,DATE_PAYEMENT) values ('hiba','123','12345','client nouveau','123','123',123,123,123,to_date('01-JAN-00','DD-MON-RR'));
Insert into FAROUK.CLIENT (NOM,PRENOM,ID,TYPEC,ADRESSE,MAIL,REVENUS,RIB,REF,DATE_PAYEMENT) values ('123','123','123','client nouveau','123','123',123,123,123,to_date('01-JAN-00','DD-MON-RR'));
REM INSERTING into FAROUK.EMPLOYE
SET DEFINE OFF;
Insert into FAROUK.EMPLOYE (CIN,NOM,PRENOM,DATENAISS,SALAIRE,POSTE,DEPART,PASSWORD,ID_CENTRE,LOGIN,CARD_UID) values ('22222222','AZE','EZA','01-JAN-00','12','Employe','Gestion des employes','0000',null,'22222222','430D87C5');
Insert into FAROUK.EMPLOYE (CIN,NOM,PRENOM,DATENAISS,SALAIRE,POSTE,DEPART,PASSWORD,ID_CENTRE,LOGIN,CARD_UID) values ('12341234','SDR','FS','01-JAN-00','123','Employe','Gestion des employes','0000',null,'12341234',null);
Insert into FAROUK.EMPLOYE (CIN,NOM,PRENOM,DATENAISS,SALAIRE,POSTE,DEPART,PASSWORD,ID_CENTRE,LOGIN,CARD_UID) values ('11111111','AZER','EA','01-JAN-00','123','Administrateur','Gestion des employes','0000',null,'11111111',null);
REM INSERTING into FAROUK.PRODUIT
SET DEFINE OFF;
Insert into FAROUK.PRODUIT (REF,TYPE,ETAT,QT,PRIX) values ('#EE5R','FE','NON RECY',800,66);
Insert into FAROUK.PRODUIT (REF,TYPE,ETAT,QT,PRIX) values ('#DG5H','PL','RECY',123,123);
Insert into FAROUK.PRODUIT (REF,TYPE,ETAT,QT,PRIX) values ('#DD4D','PL','RECY',600,44);
REM INSERTING into FAROUK.VENDRE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CENTRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAROUK"."CENTRE_PK" ON "FAROUK"."CENTRE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAROUK"."CLIENT_PK" ON "FAROUK"."CLIENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAROUK"."EMPLOYE_PK" ON "FAROUK"."EMPLOYE" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUIT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "FAROUK"."PRODUIT_PK" ON "FAROUK"."PRODUIT" ("REF") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CENTRE
--------------------------------------------------------

  ALTER TABLE "FAROUK"."CENTRE" ADD CONSTRAINT "CENTRE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FAROUK"."CENTRE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "FAROUK"."CLIENT" ADD CONSTRAINT "CLIENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FAROUK"."CLIENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "FAROUK"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FAROUK"."EMPLOYE" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "FAROUK"."PRODUIT" MODIFY ("ETAT" NOT NULL ENABLE);
  ALTER TABLE "FAROUK"."PRODUIT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "FAROUK"."PRODUIT" ADD CONSTRAINT "PRODUIT_PK" PRIMARY KEY ("REF")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FAROUK"."PRODUIT" MODIFY ("REF" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "FAROUK"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_FK1" FOREIGN KEY ("ID_CENTRE")
	  REFERENCES "FAROUK"."CENTRE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table VENDRE
--------------------------------------------------------

  ALTER TABLE "FAROUK"."VENDRE" ADD CONSTRAINT "VENNDRE_FK1" FOREIGN KEY ("CIN_EMPLOYE")
	  REFERENCES "FAROUK"."EMPLOYE" ("CIN") ENABLE;
  ALTER TABLE "FAROUK"."VENDRE" ADD CONSTRAINT "VENNDRE_FK2" FOREIGN KEY ("REF_PRODUIT")
	  REFERENCES "FAROUK"."PRODUIT" ("REF") ENABLE;
